"""Sprint 5: landing slug, url nullable

Revision ID: 3783c44ecf65
Revises: a3f79c61f196
Create Date: 2026-04-10 12:18:37.509502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3783c44ecf65'
down_revision = 'a3f79c61f196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_index('ix_landing_pages_slug', ['slug'], unique=True)
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_landing_pages_slug')
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
