"""Initial models: users, campaigns, leads, lead_history, landing_pages

Revision ID: a3f79c61f196
Revises: 
Create Date: 2026-04-07 20:18:13.189714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f79c61f196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'marketing', 'sales', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.String(length=20), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("channel IN ('email', 'social', 'search', 'display', 'referral', 'tender', 'other')", name='ck_campaigns_channel'),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'completed', 'archived')", name='ck_campaigns_status'),
    sa.CheckConstraint("target_audience IN ('b2b', 'b2g', 'mixed')", name='ck_campaigns_audience'),
    sa.CheckConstraint('budget >= 0', name='ck_campaigns_budget_positive'),
    sa.CheckConstraint('spent >= 0', name='ck_campaigns_spent_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_channel', ['channel'], unique=False)
        batch_op.create_index('ix_campaigns_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_campaigns_status', ['status'], unique=False)

    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.create_index('ix_landing_pages_campaign_id', ['campaign_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('client_type', sa.String(length=10), nullable=False),
    sa.Column('decision_maker_name', sa.String(length=200), nullable=True),
    sa.Column('decision_maker_position', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('deal_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("client_type IN ('b2b', 'b2g')", name='ck_leads_client_type'),
    sa.CheckConstraint("source IS NULL OR source IN ('landing', 'form', 'import', 'manual')", name='ck_leads_source'),
    sa.CheckConstraint("status IN ('new', 'contacted', 'qualified', 'converted', 'lost')", name='ck_leads_status'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_leads_score_range'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_leads_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_leads_client_type', ['client_type'], unique=False)
        batch_op.create_index('ix_leads_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_leads_email', ['email'], unique=False)
        batch_op.create_index('ix_leads_inn', ['inn'], unique=False)
        batch_op.create_index('ix_leads_status', ['status'], unique=False)
        batch_op.create_index('ix_leads_status_changed_at', ['status_changed_at'], unique=False)

    op.create_table('lead_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_history', schema=None) as batch_op:
        batch_op.create_index('ix_lead_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_lead_history_lead_id', ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_history', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_history_lead_id')
        batch_op.drop_index('ix_lead_history_created_at')

    op.drop_table('lead_history')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_status_changed_at')
        batch_op.drop_index('ix_leads_status')
        batch_op.drop_index('ix_leads_inn')
        batch_op.drop_index('ix_leads_email')
        batch_op.drop_index('ix_leads_created_at')
        batch_op.drop_index('ix_leads_client_type')
        batch_op.drop_index('ix_leads_campaign_id')
        batch_op.drop_index('ix_leads_assigned_to')

    op.drop_table('leads')
    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.drop_index('ix_landing_pages_campaign_id')

    op.drop_table('landing_pages')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status')
        batch_op.drop_index('ix_campaigns_created_at')
        batch_op.drop_index('ix_campaigns_channel')

    op.drop_table('campaigns')
    op.drop_table('users')
    # ### end Alembic commands ###
